set nu
syn on

set laststatus=2

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab
set autoindent
set smartindent
set number
set ruler
set backupdir=/tmp
set directory=/tmp
set ignorecase
set hls
set langmenu=zh_CN.UTF-8
set helplang=cn
set foldmethod=syntax
set nowrap

set showmatch

set synmaxcol=256

autocmd InsertLeave * se nocul
autocmd InsertEnter * se cul

set confirm

set history=50

set hlsearch
set incsearch

set gdefault

set encoding=utf-8

colorscheme torte

set guifont=Menlo:h16:cANSI

execute pathogen#infect()

autocmd vimenter * NERDTree

"powerline{
"set guifont=PowerlineSymbols\ for\ Powerline
"set nocompatible
"set t_Co=256
"let g:Powerline_symbols = 'fancy'
"}

" TagList
let Tlist_Use_Right_Window = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Show_One_File = 1
" Sort type 'name' or 'order'
let Tlist_Sort_Type = "name"
let Tlist_Compact_Format = 1
let g:tlist_php_settings = 'php;c:class;f:function'
map <D-7> :TlistToggle <CR>

" Enable omni completion.
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
autocmd FileType php setlocal omnifunc=xmlcomplete#CompletePHP

"conf for tabs, 为标签页进行的配置，通过ctrl h/l切换标签等
let mapleader = ','
nnoremap <C-l> gt
nnoremap <C-h> gT
nnoremap <leader>t : tabe<CR>

"let g:SuperTabRetainCompletionType = 2
"let g:SuperTabDefaultCompletionType = "<C-X><C-O>" 


